apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: personal-website
data:
  PORT: "5000"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  DB_NAME: "personalwebsite"
  NEXT_PUBLIC_BASE_URL: "http://app.local" 
  NEXT_PUBLIC_BACKEND_URL: "http://backend.personal-website.svc.cluster.local:5000"  
  NODE_ENV: "production"